version: '3.8'
services:
  example-game-backend:
    image: deespul/example-game-backend:${TAG}
    container_name: matchbox-example-game-backend
    restart: always
    expose:
      - 5002
    environment:
      - VIRTUAL_HOST=example.backend.matchbox.gg
      - LETSENCRYPT_HOST=example.backend.matchbox.gg
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com
      - MATCHBOX_API=${MATCHBOX_API}

networks:
  default:
    external:
      name: nginx-proxy