version: '3.8'
services:
  match-box:
    image: deespul/example-game-backend
    container_name: matchbox-example-game-backend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=matchbox.example.backend.w3champions.com
      - LETSENCRYPT_HOST=matchbox.example.backend.w3champions.com
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  mongo-db-matchbox:
    name: mongo-db-example-game-backend
